# ==========================================
# Server 1 Deployment Configurations
# ==========================================
name: speedtest-tracker-server1
working_dir: docker-apps/speedtest-tracker
compose_files:
  - docker-compose.yml
env_files:
  - .env
  - ../../.doco-cd.env
reconciliation: true

---

name: influxdb-server1
working_dir: docker-apps/influxdb/server1
compose_files:
  - compose.yml
env_files:
  - ../../../.doco-cd.env
reconciliation: true
