services:
  doco-cd:
    image: ghcr.io/kimdre/doco-cd:latest
    container_name: dococdserver
    restart: unless-stopped
    ports:
      - "8080:8080" # Webhook endpoint
      - "9120:9120" # Prometheus metrics
    environment:
      TZ: America/Chicago # Change to your actual Timezone
      WEBHOOK_SECRET: andrew123456
      POLL_CONFIG: |
        - url: https://github.com/sudbrack/testdoco.git
          reference: main
          interval: 1m
          target: server1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dococd-data:/data
    healthcheck:
      test: [ "CMD", "/doco-cd", "healthcheck" ]
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 3
