services:
  speedtest-tracker:
    image: linuxserver/speedtest-tracker:1.14.1
    container_name: speedtest-tracker
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
      - APP_KEY=${APP_KEY}
      - APP_URL=http://localhost
      - DB_CONNECTION=sqlite
    volumes:
      - ${DATASET_ROOT:-.}/speedtest-tracker:/config
    ports:
      - "81:80"
    restart: unless-stopped
